### ISSUE TITLE
RFC: textwidth=0 could mean no hardwrap

### ISSUE THREAD

**Issue by kiryph** [dbmrq/vim-bucky#2]
I was thinking about your hardcoded `78` which is used if `textwidth=0` (`tw=0`).

I can imagine that your plugin could also be used by people who actually softwrap lines
but want to place every sentence on a single line.
Also some people work together with others who use softwrap and simply follow the existing style.
This could be the behavior if `tw=0` and `wrap=on` (default of vim).

Furthermore, IMHO there is no need for a plugin specific variable to adjust the `78`.
The user should set `tw` to his liking if he wants to have hardwrapping.

**Comment by dbmrq** [comment]
Good idea, there you go. :)
